# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: myapp-dev
#   labels:
#     app: backend
#     tier: web
#     environment: dev
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#       tier: web
#       environment: dev
#   template:
#     metadata:
#       labels:
#         app: backend
#         tier: web
#         environment: dev
#     spec:
#       containers:
#         - image: aks-backend:v1.0.0 
#           imagePullPolicy: IfNotPresent
#           name: backend
#           ports:
#             - containerPort: 8000
#               protocol: TCP
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "250m"
#             limits:
#               memory: "256Mi"
#               cpu: "500m"
#       restartPolicy: Always


apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp-dev
  labels:
    app: backend
    tier: web
    environment: dev
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: web
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        tier: web
        environment: dev
    spec:
      containers:
        - image: sameed.azurecr.io/aks-backend:v1.0.1
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
